name: Dagger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dagger Run
      uses: dagger/dagger-for-github@v5
      with:
        verb: run
        args: go run ./ci
        version: "0.11.4"
